packages:
  - packages/*
  - apps/reference
  - docs

onlyBuiltDependencies:
  - esbuild
catalog:
  vite: npm:@voidzero-dev/vite-plus-core@0.2.6
  vite-plus: 0.2.6
overrides:
  vite: "catalog:"
  docs>vite: "npm:vite@^6.4.1"
  astro>vite: "npm:vite@^6.4.1"
  "@typestyles/vite>vite": "npm:vite@^6.4.1"
peerDependencyRules:
  allowAny:
    - vite
  allowedVersions:
    vite: "*"
